id: label_extractor
title: "Label Extractor"
description: "full config experiment for Mistral 7B"

# Uses xp_learn.py
file: xp_learn

epochs: 10
lr: 2e-2
batch_size: 60
logs_per_epoch: 2
# launcher: "duration=5h & cuda(mem=45G)*1 & cpu(cores=8)" # A100 JZ
launcher: "duration=3h & cuda(mem=24G)*1 & cpu(cores=8)"    #v100 JZ

# Experimental parameters
# model_name: "gpt2-small" # 12 (0-11) Transformer layers
# model_name: "gpt2-medium" # 24 (0-23) Transformer layers
# model_name: "phi-2" # 32 (0-31) Transformer layers
# model_name: "mistral-7B" # 32 (0-31) Transformer layers
# model_name: "gpt2-xl" # 48 (0-47) Transformer layers
model_name: "gpt2-medium" # 36 (0-35) Transformer layers
dataset_name: "WebNLG" 
with_context: False 
layers: 
    from: -1
    to: 6